export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';

export const UPDATE_AVATAR_URL = 'UPDATE_AVATAR_URL';

export const UPDATE_USERUPDATED_TO_IDLE = 'UPDATE_USERUPDATED_TO_IDLE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

